# Generated by Django 3.0.4 on 2020-03-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micuenta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
